server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      routes:
          - id: payment_route1 # 路由的ID，没有固定规则但要求唯一, 建议配合服务名
            uri: http://localhost:8001
            predicates:
              - Path=/payment/get/**   #访问/payment/get/**路径时会路由到cloud-payment-service服务
          - id: payment_route2
            uri: http://localhost:8001
            predicates:
              - Path=/payment/lb/**   #访问/payment/get/**路径时会路由到cloud-payment-service服务


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true #访问路径可以显示IP地址